#!/bin/bash

echo "📸 Guide pour prendre les screenshots de Luxetime"
echo "=================================================="
echo ""
echo "🚀 Étape 1 : Démarrer l'application"
echo "-----------------------------------"
echo "Dans un terminal, lancez :"
echo "  bash restart.sh"
echo ""
echo "Attendez que tout démarre (environ 10 secondes)"
echo ""
echo "🌐 Étape 2 : Ouvrir le navigateur"
echo "---------------------------------"
echo "Ouvrez Chrome ou Firefox et allez sur :"
echo "  http://localhost:3000"
echo ""
echo "📸 Étape 3 : Prendre les screenshots"
echo "------------------------------------"
echo ""
echo "1️⃣  PAGE D'ACCUEIL"
echo "   URL: http://localhost:3000"
echo "   Sauvegardez comme: docs/screenshots/home.png"
echo ""
echo "2️⃣  CATALOGUE DE PRODUITS"
echo "   URL: http://localhost:3000/products"
echo "   Sauvegardez comme: docs/screenshots/products.png"
echo ""
echo "3️⃣  DÉTAIL D'UN PRODUIT"
echo "   URL: http://localhost:3000/products/1"
echo "   Sauvegardez comme: docs/screenshots/product-detail.png"
echo ""
echo "4️⃣  PAGE DE CONNEXION"
echo "   URL: http://localhost:3000/login"
echo "   Sauvegardez comme: docs/screenshots/login.png"
echo ""
echo "5️⃣  CONNECTEZ-VOUS"
echo "   Email: test@luxetime.fr"
echo "   Mot de passe: Luxetime2024!"
echo ""
echo "6️⃣  PANIER (après connexion)"
echo "   - Ajoutez 2-3 produits au panier"
echo "   - URL: http://localhost:3000/cart"
echo "   - Sauvegardez comme: docs/screenshots/cart.png"
echo ""
echo "7️⃣  PROFIL UTILISATEUR (après connexion)"
echo "   URL: http://localhost:3000/profile"
echo "   Sauvegardez comme: docs/screenshots/profile.png"
echo ""
echo "💡 CONSEILS"
echo "-----------"
echo "- Utilisez le mode plein écran (F11)"
echo "- Zoom à 100%"
echo "- Masquez les bookmarks du navigateur (Ctrl+Shift+B)"
echo "- Format PNG pour meilleure qualité"
echo ""
echo "🎨 OUTILS RECOMMANDÉS"
echo "---------------------"
echo "Windows: Snipping Tool ou Win+Shift+S"
echo "macOS: Cmd+Shift+4"
echo "Extension: 'GoFullPage' pour capture complète"
echo ""
echo "✅ Une fois terminé"
echo "------------------"
echo "Vérifiez que tous les fichiers sont dans docs/screenshots/"
echo "Puis lancez: git add docs/screenshots/ && git commit -m 'docs: ajout screenshots' && git push"
echo ""

